[build]
  base = "."
  publish = "public"
  functions = "netlify/functions"
  command = "npm install && npm run build"

[context.production.environment]
  PAYSTACK_SECRET_KEY = "sk_live_3481588a33155f1476ac60410f3478d0d8253d3f"
   
[build]
  base = "."
  publish = "public"
  functions = "netlify/functions"
  command = "npm install && npm run build"

[context.production.environment]
  PAYSTACK_SECRET_KEY = "sk_live_3481588a33155f1476ac60410f3478d0d8253d3f"
