[build]
  base = "."
  publish = "public"
  functions = "netlify/functions"
  command = "npm install && npm run build"

[[redirects]]
  from = "/payment/callback"
  to = "/.netlify/functions/callback"
  status = 200